version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    container_name: exchange_rates_db
    environment:
      - POSTGRES_USER=me
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=exchange_rates
    ports:
      - '5432:5432'
